StartJenkins:
  Type: AWS::Lambda::Function
  Properties : 
    Code : 
      S3Bucket : jenkins-startup
      S3Key : jenkins-startup.zip
    Description : Starts jenkins server on GitHub trigger
    FunctionName : jenkins-startup
    Handler : lambda_function
    MemorySize : 128
    Runtime : python3.7
    Timeout : 10

StopJenkins:
  Type: AWS::Lambda::Function
  Properties : 
    Code : 
      S3Bucket : jenkins-startup
      S3Key : jenkins-startup.zip
    Description : Stops jenkins
    FunctionName : jenkins-startup
    Handler : stop_jenkins
    MemorySize : 128
    Runtime : python3.7
    Timeout : 10

StopJenkinsTimer:
  Type: AWS::Events::Rule
  Properties : 
    Description : Stop Jenkins after 1 hour
    Name : jenkins-stop-timer
    RoleArn : String
    State : ENABLED
    Targets : 
      - Target